version: "2"
services:
    calender_server:
        build: .
        ports: 
            - "87:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - calender_db
        networks:
            - proxy_my-network
    calender_db:
        build:
            context: .
            dockerfile: Dockerfile-mysql
        ports: 
            - "33067:3306"
        environment:
            MYSQL_LOWER_CASE_TABLE_NAMES: 2
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./persistent:/var/lib/mysql
        networks:
            - proxy_my-network
networks:
  proxy_my-network:
    external: true
volumes:
    persistent:

